name: Bump version
on:
  push:
    branches:
      - master

env:
  WITH_V: true
  DEFAULT_BUMP: patch
  INITIAL_VERSION: 0.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}